to_see = ['Europe', 'Asia', 'Africa', 'Portland', 'Austin']
print(to_see)
print(sorted(to_see))
print(to_see)
print(sorted(to_see, reverse=True))
print(to_see)
to_see.reverse()
print(to_see)
to_see.reverse()
print(to_see)
to_see.sort()
print(to_see)
to_see.sort(reverse=True)
print(to_see)